config/routes.rb
Rails.application.routes.draw do
  
  resources :todo_lists do
    resources :todo_items do
      member do
        patch :complete
      end
    end
  end
  
  root "todo_lists#index"
end

app/models/todo_item.rb
class TodoItem < ActiveRecord::Base
  belongs_to :todo_list
  
  def completed?
      !completed_at.blank?
  end
end

app/models/todo_list.rb
class TodoList < ActiveRecord::Base
    has_many :todo_items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
    before_action :set_todo_list 
    before_action :set_todo_item, only: [:show, :edit, :update, :destroy]

    def create
       @todo_item = @todo_list.todo_items.create(todo_item_params)
       redirect_to @todo_list
    end
    
    def destroy
        if @todo_item.destroy
            flash[:success] = "Category item was deleted."
        else
            flash[:error] = "Category could not be deleted."
        end
        redirect_to @todo_list
    end
    
    def show
    end
    
    def edit
    end
    
    def update
        respond_to do |format|
          if @todo_list_todo_item.update(todo_list.todo_item_params)
            format.html { redirect_to @todo_list_todo_item, notice: 'Category was successfully updated.' }
            format.json { render :show, status: :ok, location: @todo_list_todo_item }
          else
            format.html { render :edit }
            format.json { render json: @todo_item.errors, status: :unprocessable_entity }
          end
        end
    end
    
    def complete
    @todo_item.update_attribute(:completed_at, Time.now)
    redirect_to @todo_list, notice: "Member completed"
    end

    private
    
    def set_todo_list
       @todo_list = TodoList.find(params[:todo_list_id])
    end
    
    def set_todo_item
        @todo_item = @todo_list.todo_items.find(params[:id])
    end
    
    def todo_item_params
        params[:todo_item].permit(:content, :email, :url, :phone, :location, :skill)
    end
    
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: [:show, :edit, :update, :destroy]

  # GET /todo_lists
  # GET /todo_lists.json
  def index
    @todo_lists = TodoList.all
  end

  # GET /todo_lists/1
  # GET /todo_lists/1.json
  def show
  end

  # GET /todo_lists/new
  def new
    @todo_list = TodoList.new
  end

  # GET /todo_lists/1/edit
  def edit
  end

  # POST /todo_lists
  # POST /todo_lists.json
  def create
    @todo_list = TodoList.new(todo_list_params)

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully created.' }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_lists/1
  # PATCH/PUT /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1
  # DELETE /todo_lists/1.json
  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Todo list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = TodoList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_list_params
      params.require(:todo_list).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UTU - Members</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet' type='text/css'>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>

<div class="container">

  <center>
    <img src="http://utu.agency/wp-content/uploads/2016/07/logo.svg" width="90" height="auto" /><br>
    <small>utu.agency</small>
	</center>
	
	<%= yield %>
	

</div>
	<footer>
	  <center>
	  <p><a href="https://github.com/leandromac/MemberList" target="_blank"><img src="http://untv.github.io/assets/images/github-icon-black.svg" width="30" height="30"></a></p>
	  </center>  
	</footer>
</body>
</html>

app/views/todo_items/_form.html.erb
<%= form_for([@todo_list, @todo_list.todo_items.build]) do |f| %>
    <%= f.text_field :content, placeholder: "Name" %>
    <%= f.text_field :email, placeholder: "Email" %>
    <%= f.text_field :phone, placeholder: "Phone" %>
    <%= f.text_field :url, placeholder: "Portfolio" %>
    <%= f.text_field :location, placeholder: "Location" %>
    <%= f.text_field :skill, placeholder: "Skills" %>
    <%= f.submit 'Create new member' %>
<% end %>

app/views/todo_items/_todo_item.html.erb
<div class="row clearfix">
    <% if todo_item.completed? %>

        <div class="todo_item">
            <p style="opacity: 0.4;"><strike><%= todo_item.content %></strike></p>
        </div>
        <div class="trash">
            <%= link_to todo_list_todo_item_path(@todo_list, todo_item.id), method: :delete, data: { confirm: "Are you sure?" } do %>
                <i style="opacity:0.4;" class="fa fa-trash"></i>
            <% end %>
        </div>
    <% else %>
        <div class="complete">
			<p style="color:#FFF"><%= todo_item.id %></p>
		</div>
        <div class="todo_item">
            

            <p><strong><%= todo_item.content %></strong> <small>(<%= todo_item.location %>)</small><br>
                <strong><small>phone:</small></strong> <%= todo_item.phone %>, <strong><small>email:</small></strong><%= todo_item.email %><br>
            <strong><small>url:</small></strong> <%= todo_item.url %>
            </p>
        </div>
        <div class="trash">
            <%= link_to todo_list_todo_item_path(@todo_list, todo_item.id), method: :delete, data: { confirm: "Are you sure?" } do %>
                <i style="opacity:0.4;" class="fa fa-trash"></i>
            <% end %>
        </div>
        
    <% end %>
</div>

app/views/todo_items/edit.html.erb
<h1 class="todo_item_content">Edit Todo List</h1>

<div class="forms">
    <%= render 'form' %>
</div>

<div class="links">
    <%= link_to 'Cancel', todo_list_todo_items_path %>
</div>

app/views/todo_items/show.html.erb
<h1 class="todo_list_title">Edit Todo List</h1>

<div class="forms">
    <%= render 'form' %>
</div>

<div class="links">
    <%= link_to 'Cancel', todo_list_todo_items_path %>
</div>

app/views/todo_lists/_form.html.erb
<%= form_for(@todo_list) do |f| %>
  <% if @todo_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h2>

      <ul>
      <% @todo_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :title, placeholder: "Type a title" %>
  </div>
  <div class="field">
    <%= f.text_area :description, placeholder: "Description" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todo_lists/edit.html.erb
<h1 class="todo_list_title">Edit category</h1>

<div class="forms">
    <%= render 'form' %>
</div>

<div class="links">
    <%= link_to 'Cancel', todo_lists_path %>
</div>

app/views/todo_lists/index.html.erb
<% @todo_lists.each do |todo_list| %>
  <div class="index_row clearfix">
    <h2 class="todo_list_title"><%= link_to todo_list.title, todo_list %></h2>
    <p class="todo_list_sub_title"><%= todo_list.description %></p>
  </div>
<% end %>

<div class="links">
  <%= link_to "New category", new_todo_list_path %>
</div>

app/views/todo_lists/new.html.erb
<h1 class="todo_list_title">New category</h1>

<div class="forms">
    <%= render 'form' %>
</div>

<div class="links">
    <%= link_to 'Back', todo_lists_path %>
</div>

app/views/todo_lists/show.html.erb
<p id="notice"><%= notice %></p>

<h2 class="todo_list_title"><%= @todo_list.title %></h2>
<p class="todo_list_sub_title"><%= @todo_list.description %></p>

<div id="todo_items_wrapper">
	<%= render @todo_list.todo_items %>
	<div id="form">
		<%= render "todo_items/form" %>
	</div>
</div>

<div class="links">
	<%= link_to 'Edit', edit_todo_list_path(@todo_list) %> |
	<%= link_to 'Delete', todo_list_path(@todo_list), method: :delete, data: { confirm: "Are you sure?" }
 %> |
  <%= link_to 'Back', todo_lists_path %>
</div>